In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [3]:
df = pd.read_csv('ecommerce_bigdata.csv')

In [4]:
df.head()

,TransactionID,Date,Region,ProductCategory,CustomerType,Sales,Profit
0,TX0001,6/16/2026,Eastern,Electronics,Wholesale,4924,359.44
1,TX0002,2/12/2026,Central,Electronics,Retail,3283,944.32
2,TX0003,3/1/2026,Northern,Food,Online,4049,967.10
3,TX0004,6/3/2026,Western,Household Products,Online,4331,434.57
4,TX0005,1/21/2026,Western,Household Products,Retail,3283,340.48

In [5]:
df.isnull().sum()

TransactionID      0
Date               0
Region             0
ProductCategory    0
CustomerType       0
Sales              0
Profit             0
dtype: int64

In [6]:
df.describe()

             Sales       Profit
count   200.000000   200.000000
mean   2567.190000   456.367350
std    1528.736925   346.853151
min      56.000000     5.130000
25%    1200.500000   173.967500
50%    2428.000000   379.330000
75%    4052.000000   675.000000
max    4998.000000  1377.040000

In [ ]:
#Data visualization
import matplotlib.pyplot as plt

# Data visualization
plt.style.use('seaborn-v0_8-darkgrid')
fig, axes = plt.subplots(2, 2, figsize=(14, 10)) 
# Distribution of Sales:
sns.histplot(df['Sales'], bins=30, kde=True, ax=axes[0, 0])
axes[0, 0].set_title('Distribution of Sales')   
axes[0, 0].set_xlabel('Sales')
axes[0, 0].set_ylabel('Frequency')
# Distribution of Profit:
sns.histplot(df['Profit'], bins=30, kde=True, ax=axes[0, 1])
axes[0, 1].set_title('Distribution of Profit')
axes[0, 1].set_xlabel('Profit')
axes[0, 1].set_ylabel('Frequency')
# sales by product category (Boxplot) in the third grid
sns.boxplot(x='ProductCategory', y='Sales', data=df, ax=axes[1, 0])      
axes[1, 0].set_title('Sales by Product Category')
axes[1, 0].set_xlabel('Product Category')
axes[1, 0].set_ylabel('Sales')
fig, axes = plt.subplots(2, 2, figsize=(14, 10)) 
#Distribution of Sales:
sns.histplot(df['Sales'], bins=30, kde=True, ax=axes[0, 0])
axes[0, 0].set_title('Distribution of Sales')   
axes[0, 0].set_xlabel('Sales')
axes[0, 0].set_ylabel('Frequency')
#Distribution of Profit:
sns.histplot(df['Profit'], bins=30, kde=True, ax=axes[0, 1])
axes[0, 1].set_title('Distribution of Profit')
axes[0, 1].set_xlabel('Profit')
axes[0, 1].set_ylabel('Frequency')
#sales by product category (Boxplot) in the third grid
sns.boxplot(x='ProductCategory' , y= 'Sales' , data=df , ax=axes[1,0])      
axes[1, 0].set_title('Sales by Product Category')
axes[1, 0].set_xlabel('Product Category')
axes[1, 0].set_ylabel('Sales')

NameError: name 'plt' is not defined